# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions:
    - autolink
gems:
  - jekyll-redirect-from

# Setup
baseurl: /

# Page settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
